/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PurposeRouteImport } from './routes/purpose'
import { Route as IndexRouteImport } from './routes/index'

const PurposeRoute = PurposeRouteImport.update({
  id: '/purpose',
  path: '/purpose',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/purpose': typeof PurposeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/purpose': typeof PurposeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/purpose': typeof PurposeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/purpose'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/purpose'
  id: '__root__' | '/' | '/purpose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PurposeRoute: typeof PurposeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/purpose': {
      id: '/purpose'
      path: '/purpose'
      fullPath: '/purpose'
      preLoaderRoute: typeof PurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PurposeRoute: PurposeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
